name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
        name: Check out code
        
      - name: Increment version
        run: |
          # Read the version from version.txt
          VERSION=$(cat version.txt)
          echo "Original version: $VERSION"
          
          # Split the version number into array based on the '.' delimiter
          IFS='.' read -ra VER <<< "$VERSION"
          
          # Increment the patch version
          PATCH=$((VER[2]+1))
          NEW_VERSION="${VER[0]}.${VER[1]}.$PATCH"
          echo "New version: $NEW_VERSION"
          
          # Expose the new version to the global environment for subsequent steps
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
  
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: gilibee/hello-world-docker:${{ env.VERSION }}
          tags: ${{ env.VERSION }}, latest
          registry: registry-url.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Increment version
        run: |
          # Optionally: Update the version.txt file with the new version
          echo $NEW_VERSION > version.txt
          echo "version updated: $NEW_VERSION"
